# Generated by Django 3.2.22 on 2023-10-18 02:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_test', '0004_imageres'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeartbeatRes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(default=None, max_length=128, null=True)),
                ('is_http', models.BooleanField(default=None, null=True)),
                ('sequence_len', models.IntegerField(default=None, null=True)),
                ('sequence_mean', models.DecimalField(decimal_places=10, default=None, max_digits=20, null=True)),
                ('create_time', models.DateField(default=datetime.datetime.now)),
            ],
        ),
    ]
