# Generated by Django 2.1.8 on 2023-10-17 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flow_cut', '0006_alter_pcaps_cut_name'),
        ('flow_cut', '0007_pcap_cut'),
    ]

    operations = [
    ]
