# Generated by Django 2.1.8 on 2023-10-17 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flow_cut', '0008_merge_20231017_0140'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pcaps_cut',
        ),
    ]
