# Generated by Django 2.1.8 on 2023-10-17 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feature_extract', '0007_alter_tls_feature_name'),
        ('feature_extract', '0008_auto_20210909_0319'),
    ]

    operations = [
    ]
